// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Id int32 `path:"id"`
}

type SearchReply struct {
	Id      int32    `json:"id"`
	Name    string   `json:"name"`
	Hobbies []string `json:"hobbies"`
}

type SearchOrderReq struct {
	Id int32 `path:"id"`
}

type SearchOrderReply struct {
	Id      int32    `json:"id"`
	Name    string   `json:"name"`
	Hobbies []string `json:"hobbies"`
}
