// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_zero_study/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/User/get/:id",
				Handler: getUserInfoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/user_login",
				Handler: loginHandler(serverCtx),
			},
		},
	)
}
