// Code generated by goctl. DO NOT EDIT.
package types

type UserReq struct {
	Id int32 `path:"id"`
}

type UserReply struct {
	Id      int32    `json:"id"`
	Name    string   `json:"name"`
	Hobbies []string `json:"hobbies"`
}

type LoginReq struct {
	Id       int32  `json:"id"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id        int32  `json:"id"`
	SecretKey string `json:"secretkey"`
}
